export const galleryProjects = [
  {
    id: 101,
    title: "Gallery Image 1",
    category: "Gallery",
    image: "/logos/gallery/DSC_8385-2.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "",
    results: [],
  },
  {
    id: 102,
    title: "Gallery Image 2",
    category: "Gallery",
    image: "/logos/gallery/DSC_8389.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "",
    results: [],
  },
  {
    id: 103,
    title: "Gallery Image 3",
    category: "Gallery",
    image: "/logos/gallery/DSC_8412.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "",
    results: [],
  },
  {
    id: 104,
    title: "Gallery Image 4",
    category: "Gallery",
    image: "/logos/gallery/DSC_8427.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "",
    results: [],
  },
  {
    id: 105,
    title: "Gallery Image 5",
    category: "Gallery",
    image: "/logos/gallery/DSC_8429.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "",
    results: [],
  },
  {
    id: 106,
    title: "Gallery Image 6",
    category: "Gallery",
    image: "/logos/gallery/DSC_8455.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "",
    results: [],
  },
  {
    id: 107,
    title: "Gallery Image 7",
    category: "Gallery",
    image: "/logos/gallery/DSC_8493.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "",
    results: [],
  },
  {
    id: 108,
    title: "Gallery Image 8",
    category: "Gallery",
    image: "/logos/gallery/DSC_8499.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "",
    results: [],
  },
  {
    id: 109,
    title: "Gallery Image 9",
    category: "Gallery",
    image: "/logos/gallery/DSC_8509-2.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "",
    results: [],
  },
  {
    id: 110,
    title: "Gallery Image 10",
    category: "Gallery",
    image: "/logos/gallery/Business Without Digital Strategy.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "",
    results: [],
  },
];

export const marketingProjects = [
  {
    id: 201,
    title: "inkstories logo-02",
    category: "Marketing",
    image: "/logos/inkstories logo-02.png",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "",
    results: [],
  },
  {
    id: 202,
    title: "CLSSYDINE",
    category: "Marketing",
    image: "/logos/CLSSYDINE.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "",
    results: [],
  },
  {
    id: 203,
    title: "B21",
    category: "Marketing",
    image: "/logos/B21.png",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "",
    results: [],
  },
  {
    id: 204,
    title: "Amedore",
    category: "Marketing",
    image: "/logos/Amedore.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "",
    results: [],
  },
];

export const designProjects = [
  {
    id: 301,
    title: "Business Without Digital Strategy",
    category: "Design",
    image: "/logos/design/Business Without Digital Strategy.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "Accentic Solutions",
    results: [],
  },
  {
    id: 303,
    title: "Holi Special Offer-1",
    category: "Design",
    image: "/logos/design/Holi Special Offer-1.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "B21",
    results: [],
  },
  {
    id: 304,
    title: "Home Delivery Available2-1",
    category: "Design",
    image: "/logos/design/Home Delivery Available2-1.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "B21",
    results: [],
  },
  {
    id: 305,
    title: "Bridal Makeup",
    category: "Design",
    image: "/logos/design/Bridal Makeup.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "B21",
    results: [],
  },
  {
    id: 306,
    title: "Bridal Makeup 2",
    category: "Design",
    image: "/logos/design/Bridal Makeup 2.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "B21",
    results: [],
  },
  {
    id: 307,
    title: "Piercing Available2",
    category: "Design",
    image: "/logos/design/Piercing Available2.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "B21",
    results: [],
  },
  {
    id: 308,
    title: "Raja Offer-1",
    category: "Design",
    image: "/logos/design/Raja Offer-1.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "B21",
    results: [],
  },
  {
    id: 309,
    title: "Piercing Available3",
    category: "Design",
    image: "/logos/design/Piercing Available3.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "B21",
    results: [],
  },
  {
    id: 310,
    title: "Summer Offer AD-1",
    category: "Design",
    image: "/logos/design/Summer Offer AD-1.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "B21",
    results: [],
  },
  {
    id: 311,
    title: "Raja B21 offer",
    category: "Design",
    image: "/logos/design/Raja B21 offer.jpg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "B21",
    results: [],
  },
  {
    id: 312,
    title: "b21-2",
    category: "Design",
    image: "/logos/design/b21-2.jpeg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "B21",
    results: [],
  },
  {
    id: 313,
    title: "b21-1",
    category: "Design",
    image: "/logos/design/b21-1.jpeg",
    description: "",
    technologies: [],
    liveUrl: "",
    githubUrl: "",
    date: "",
    client: "B21",
    results: [],
  },
];

export const portfolioVideos = [
  {
    id: "1",
    title: "Project Showcase - TechStart E-Commerce",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: "2",
    title: "GreenLife Brand Identity Design Process",
    youtubeUrl: "https://www.youtube.com/watch?v=9bZkp7q19f0",
  },
  {
    id: "3",
    title: "FinanceFlow Dashboard Demo",
    youtubeUrl: "https://www.youtube.com/watch?v=jNQXAC9IVRw",
  },
  {
    id: "4",
    title: "RestaurantPro Management System Overview",
    youtubeUrl: "https://www.youtube.com/watch?v=3JZ_D3ELwOQ",
  },
  {
    id: "5",
    title: "FitTracker Mobile App Walkthrough",
    youtubeUrl: "https://www.youtube.com/watch?v=l482T0yNkeo",
  },
  {
    id: "6",
    title: "Creative Design Highlights 2024",
    youtubeUrl: "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
  },
  {
    id: "7",
    title: "Marketing Campaign Success Story",
    youtubeUrl: "https://www.youtube.com/watch?v=V-_O7nl0Ii0",
  },
];

export const projects = [
  {
    id: 1,
    title: "TechStart E-Commerce Platform",
    category: "Web Development",
    description:
      "A comprehensive e-commerce solution with advanced features including real-time inventory management, multi-payment gateway integration, and AI-powered product recommendations.",
    image: "/logos/Amedore.jpg?height=300&width=600",
    technologies: ["React", "Node.js", "MongoDB", "Stripe", "AWS"],
    liveUrl: "#",
    githubUrl: "#",
    date: "2024",
    client: "TechStart Inc.",
    results: [
      "300% increase in sales",
      "50% faster checkout process",
      "99.9% uptime",
    ],
  },
  {
    id: 3,
    title: "FinanceFlow SaaS Dashboard",
    category: "Web Development",
    description:
      "A sophisticated financial analytics dashboard with real-time data visualization, automated reporting, and advanced security features.",
    image: "/logos/CLSSYDINE.jpg?height=400&width=600",
    technologies: ["Vue.js", "D3.js", "Python", "PostgreSQL", "Docker"],
    liveUrl: "#",
    githubUrl: "#",
    date: "2023",
    client: "FinanceFlow Ltd.",
    results: ["60% time savings", "Real-time insights", "Enterprise security"],
  },
  {
    id: 4,
    title: "FitTracker Mobile App",
    category: "Gallery",
    description:
      "Cross-platform fitness tracking application with social features, workout planning, and integration with wearable devices.",
    image: "/logos/Amedore.jpg?height=300&width=600",
    technologies: ["React Native", "Firebase", "Redux", "HealthKit"],
    liveUrl: "#",
    githubUrl: "#",
    date: "2023",
    client: "FitTracker Inc.",
    results: ["100K+ downloads", "4.8 app store rating", "Featured by Apple"],
  },
  {
    id: 6,
    title: "RestaurantPro Management System",
    category: "Web Development",
    description:
      "Comprehensive restaurant management system with POS integration, inventory tracking, staff scheduling, and customer analytics.",
    image: "/logos/B21.png?height=400&width=600",
    technologies: ["Angular", "Express.js", "MySQL", "Socket.io"],
    liveUrl: "#",
    githubUrl: "#",
    date: "2022",
    client: "RestaurantPro Chain",
    results: [
      "30% efficiency increase",
      "Real-time operations",
      "Cost optimization",
    ],
  },
].concat(galleryProjects, marketingProjects, designProjects);

export const categories = ["All", "Web Development", "Design", "Marketing", "Gallery"];